---
title       : Data visualization
subtitle    : Interactive charts
author      : Ivan Liu
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
license     : by-nc-sa
github      :
  user      : ivanliu1989
  repo      : interactive_charts
---

## Read-And-Delete

1. Read and follow the official [Google Chart API documentation](https://developers.google.com/chart/) and [Terms of Service](https://developers.google.com/readme/terms)


--- .class #id 

## A simple table

```{r, results='asis',comment=NA, echo=FALSE}
library(xtable)
options(xtable.type='html')
xtable(head(mtcars))
```

---

## A simple line plot

```{r, results='asis', comment = NA,message = F, echo = F}
require(rCharts)
require(knitr)
r1 <- rPlot(mpg ~ wt | am + vs, data = mtcars, type = "point", color = "gear")
r1
```

---

## Interactive plot 1

```{r,results = 'asis', comment = NA, message = F, echo = F}
map3 <- Leaflet$new()
map3$setView(c(51.505, -0.09), zoom = 13)
map3$marker(c(51.5, -0.09), bindPopup = "<p> Hi. I am a popup </p>")
map3$marker(c(51.495, -0.083), bindPopup = "<p> Hi. I am another popup </p>")
map3
```

---

## Interactive plot 2
```{r, results='asis', comment = NA,message = F, echo = F}
data(economics, package = "ggplot2")
econ <- transform(economics, date = as.character(date))
m1 <- mPlot(x = "date", y = c("psavert", "uempmed"), type = "Line", data = econ)
m1$set(pointSize = 0, lineWidth = 1)
m1
```

---

## Interactive plot 3
```{r, results='asis', comment = NA,message = F, echo = F}
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, group = "Eye", data = hair_eye_male, type = "multiBarChart")
n1
```

---

## Interactive plot 4
```{r, results='asis', comment = NA,message = F, echo = F}
require(reshape2)
uspexp <- melt(USPersonalExpenditure)
names(uspexp)[1:2] = c("category", "year")
x1 <- xPlot(value ~ year, group = "category", data = uspexp, type = "line-dotted")
x1
```

---

## Interactive plot 5
```{r, results='asis', comment = NA,message = F, echo = F}
h1 <- hPlot(x = "Wr.Hnd", y = "NW.Hnd", data = MASS::survey, type = c("line", "bubble", "scatter"),
            group = "Clap", size = "Age")
h1
```

---

## Interactive plot 6
```{r, results='asis', comment = NA,message = F, echo = F}
usp = reshape2::melt(USPersonalExpenditure)
# get the decades into a date Rickshaw likes
usp$Var2 <- as.numeric(as.POSIXct(paste0(usp$Var2, "-01-01")))
p4 <- Rickshaw$new()
p4$layer(value ~ Var2, group = "Var1", data = usp, type = "area", width = 560)
# add a helpful slider this easily; other features TRUE as a default
p4$set(slider = TRUE)
p4
```